- lm_eval/base.py
- lm_eval/models/gpt2.py
- lm_eval/models/t0.py
- lm_eval/models/t5.py
This PR is to fix stopping criteria to be optional, and modify T0 and T5 to BaseLM.
> Fixing stopping criteria & Modifying T0, T5 to BaseLM

- lm_eval/models/t5.py
- lm_eval/tasks/blimp.py
This PR is to add null prompt support for T5, and add BLIMP task template.
Used this [promptsource repo](https://github.com/Urmish/promptsource/tree/urmish/blimp) to test T5.
@najoungkim  @Urmish
> Added null prompt support for T5 & Added BLIMP task template

- lm_eval/tasks/__init__.py
- lm_eval/tasks/gem_xsum.py
Add GM/xsum.
Two questions:
- Is "." a good stopping criterion? It seems like most of the examples end in '.' except for a few (~10 out of ~400 for each split). All the examples in xum are supposed to be 'one sentence.
- Should I set the max length?
> Add GEM/xsum

- lm_eval/tasks/__init__.py
- lm_eval/tasks/gem_mlsum.py
- lm_eval/tasks/mlsum.py
Only doubts I have are around:
- Is "." a good stopping criteria?
- Is max_length set to 120 good?
> Add MLsum Tasks

- lm_eval/tasks/__init__.py
Just a small nit. Was about to fix it, Sorry!
> Fix tasks for GEM/mlsum

- lm_eval/base.py
(This never got added before the previous merge.)
> Fix naming

- lm_eval/tasks/__init__.py
- lm_eval/tasks/lince.py
Test locally on gpt2 and T5-small using prompts from this [PR#757](https://github.com/bigscience-workshop/promptsource/pull/757) from promptsource.
> Add lince sentiment analysis task.

- lm_eval/evaluator.py
- lm_eval/models/t0.py
- lm_eval/models/t5.py
- main.py
* Added parser arg for parallel
* Wired arg to models
* Added doc for the outputfile
> Add parser arg for parallel

- lm_eval/tasks/hans.py
* Added heuristic/subcase from hf doc to our logged example.
> Add additional info to example logging for analysis (`HANS`)

- main.py
- scripts/agg2slim.py
* Added slim results
* Added script to map old aggregation to the slimmer files
* Changed codecarbon setup to use a context manager.
* This seems to hang less and will close even if there is an issue
* Found and fixed an issue with the previous saving of results
* Examples were being saved instead of the config.
> Housekeeping: slim results, codecarbon context, fix config bug

- lm_eval/tasks/superglue.py
Related Issue: #65 and [comment](https://github.com/bigscience-workshop/lm-evaluation-harness/issues/65#issuecomment-1130537571)
> Fix `copa` ignored docs

- setup.py
Updates the `transformers` dependency to install from their `main` git branch.
> Pin `transformers` to main repo

- lm_eval/base.py
- lm_eval/tasks/glue.py
- lm_eval/tasks/superglue.py
- Adds byte-length accuracy normalization to the `PromptSourceTask`'s auto evaluation process.
-  Updates `glue.py` and `superglue.py` to account for this change.
> Add byte-length accuracy normalization

- lm_eval/tasks/crows_pairs_multilingual.py
- Updates `DATASET_PATH` to reflect dataset location update (see related [thread](https://github.com/bigscience-workshop/promptsource/pull/748#discussion_r870258896) in `promptsource`).
> Rename `crows_pairs_multilingual` dataset path

- lm_eval/models/huggingface.py
move tokens to device for hf seq2seq
> move tokens to device for hf seq2seq

- setup.py
we haven't changed to main yet
> we haven't changed to main yet

- lm_eval/tasks/__init__.py
> Change BioTask to use correct PromptSource path.

- scripts/eval_zeroshot.sh
- scripts/print_table.py
- Adds script for running zeroshot evaluation with wall clock time output
- Adds script for parsing slim files and printing table
> Add scripts for running timed zeroshot evaluation and printing table from slim files

- setup.py
- Fixes dependency resolution failures when running `pip install -e ...`
- Removes unused dependencies from `master` branch: `jsonlines`, `lm_dataformat`, `pybind11`
> Resolve dependency chain issue

- lm_eval/tasks/__init__.py
- lm_eval/tasks/flores_101_mt.py
Added a task script for Flores_101 (for MT - one already exists, but just in terms of perplexity).
> Add task for Flores_101 (for MT)

- lm_eval/tasks/__init__.py
- lm_eval/tasks/superglue.py
- Adds SuperGLUE RTE as the [prompts for GLUE `rte`](https://github.com/bigscience-workshop/promptsource/blob/main/promptsource/templates/glue/rte/templates.yaml) differ from [prompts for SuperGLUE `rte`](https://github.com/bigscience-workshop/promptsource/blob/main/promptsource/templates/super_glue/rte/templates.yaml).
> Add SuperGLUE RTE

- main.py
- Updates the CLI arg flag`use_cache` to store a `True` bool value, unlike the previous `no_cache` option.
> Flip `use_cache` default to store true

- lm_eval/models/huggingface.py
- Adds support for `accelerate` `device_map` options for finer grain control.
- This addresses the problem of running out of memory on the 0-th rank GPU because input tokens share the same memory space as some of the partitioned parameters - simply set `device_map_options="balanced_low_0"`.
> Add `device_map_option` to `accelerate` args

- setup.py
update setup.py with new default bigbio branch
> update setup.py with new default bigbio branch

- .github/workflows/python-app.yml
- README.md
- lm_eval/api/utils.py
- lm_eval/evaluator.py
- main.py
- scripts/write_out.py
- setup.py
- tests/test_evaluator.py
- tests/test_misc.py
- tests/test_version_stable.py
- Re-introduces `seed` configuring with the default set to `1234` for backward compatibility.
> Make `seed` configurable

- lm_eval/models/huggingface.py
Adds revision argument to `AutoConfig.from_pretrained()`
> Add revision to AutoConfig initialization

- README.md
- main.py
Enhances readability with line breaks.
> Re-format CLI help docs for readability

- lm_eval/tasks/__init__.py
- lm_eval/tasks/diabla.py
- lm_eval/tasks/flores_101.py
Corrected bug: fewshot examples were using the same source and target sentence
Added task: wmt_hi2en - take fewshot examples from wmt hi-en dev set
> Corrected bug in Flores fewshot tasks and added flores task

- README.md
- lm_eval/api/task.py
- lm_eval/tasks/__init__.py
- lm_eval/tasks/amazon_reviews_multi.py
Add Amazon Review Multi datasets and tasks.
Enable load_from_disk function from datasets library to load dataset.
> Add Amazon Reviews tasks and load_from_disk function
