- lm_eval/base.py
- scripts/write_out.py
- Updates the few-shot example separator following suggestion from Webson & Pavlick, "[Do Prompt-Based Models Really Understand the Meaning of Their Prompts?]( https://arxiv.org/pdf/2109.01247.pdf)". 
- Updates `scripts.write_out` to handle fewshot logging info returned from `PromptSourceTask.fewshot_context`
> Add `"\n###\n"` example separator

- lm_eval/models/gptj.py
Missing `eot_token` property caused runtime error.
> Add `eot_token` property to gpt-j

- lm_eval/base.py
With this fix it's possible to run write_out for datasets without a training split. Before it was only possible for `--num_fewshot 0`.
> Fixed issue with write_out for datasets without a training split

- lm_eval/base.py
- lm_eval/models/gpt2.py
- lm_eval/models/gptj.py
- lm_eval/models/t5.py
- lm_eval/tasks/drop.py
- lm_eval/tasks/e2e_nlg_cleaned.py
- lm_eval/tasks/gem_asset_turk.py
- lm_eval/tasks/gem_mlsum.py
- lm_eval/tasks/gem_webnlg.py
- lm_eval/tasks/gem_xsum.py
- lm_eval/tasks/glue.py
- lm_eval/tasks/wino_bias.py
- templates/new_task.py
- Ensures `max_generation_length`  is handled properly for both `gpt` and `t5` style models.
- Removes unused `fewshot_context` in `Task`
- Removes `stopping_criteria` usages to nudge implementers into setting `max_generation_length`. Updates `new_task` template accordingly.
> Fix max generation limit

- lm_eval/tasks/gem_xsum.py
I removed stopping_criteria  and set max_generation_length to 64 so that the models will generate the prediction until either eos or 64th tokens.
For GEN/xsum, the summary is supposed to be one sentence long. If we don't set max_generation_length, the model keeps generating the sentences. So, probably it's best to max_generation_length to 64, which is enough for even a long sentence.
> Remove stopping_criteria and set max_generation_length to 64

- main.py
* Adds datatime in iso format at the end of the name
* Removes a duplicate arg to evaluate (I think it got added in a merge.)
> Add datetime to log so that we don't have name clashes

- lm_eval/evaluator.py
During complete task evaluation, constructing few-shot contexts with logging info and model requests can take a non-trivial amount of time. Currently, users have no idea that this is going on. This PR adds a display for progress tracking during this stage of evaluation.
> Add progress bar to track few-shot context and request building

- lm_eval/base.py
- lm_eval/models/gpt2.py
- lm_eval/tasks/__init__.py
- lm_eval/tasks/flores_101.py
- main.py
[gsarti/flores_101](https://huggingface.co/datasets/gsarti/flores_101) is a dataset with 102 languages we will use for language modeling.
* Adds the 102 language subsets dynamically
* The prompt is null -- just the sentence itself -- as this dataset is only used for language modeling (LM).
* Therefore, this task doesn't actually interface with `promptsource`. (I don't see a good reason to add a no-opt prompt.)
* I have run gpt2 on `eng`, `afr`, `zul`.
* Updated `PerplexityTask` to work with our new evaluation pipeline
* Bug Fix: Add back the printing out of the metric table
On a small batch, the perplexity of `zul` is much higher than `eng`. `afr` is in the middle.
```
|        Task         |Prompt|Version|    Metric     |      Value      |   |Stderr| …
```
> Add `gsarti/flores101` tasks

- lm_eval/evaluator.py
- main.py
* Currently we store all examples during all of evaluation.
* In this PR, we log examples more frequently s.t. there is less ram usage
* In the very large datasets, holding all exampels (datasetsize x #prompts) might start to become problematic
* The example format will now be `.jsonl` -- its easy to read visually and can be processed with many libraries or something like `[json.loads(line) for line in file.readlines()]`
> Using `logging` for examples instead of `json`

- lm_eval/models/huggingface.py
- lm_eval/utils.py
- tests/test_utils.py
- Adds rolling loglikelihood to `AutoSeq2SeqLM` which is required by `PreplexityTask`s.
- Refactors `AutoSeq2SeqLM.loglikelihood` to match the structure of `AutoCausalLM.loglikelihood` 
- Moves token-level loglikelihood logic into `_loglikelihood_tokens` 
Related Issue: #64
> Add `loglikelihod_rolling` to `AutoSeq2SeqLM`

- lm_eval/models/huggingface.py
Tokens were never put on the user-specified device which resulted in the following error when `--device cuda`: 
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
```
> Put tokens on `device`

- main.py
The model name is not extracted correctly when the `pretrained` argument is not the last one passed to `model_args`.
Current behavior:
```
python main.py \
--model hf-causal \
--model_args pretrained=gpt2,half=False \
--tasks wnli --device cpu
```
generates files such as:
```
slim-False_wnli_0_1234_2022-06-16T17:37:36.261571.json
examples-False_wnli_0_1234_2022-06-16T17:37:36.261571.jsonl
```
This fix allows the `pretrained` arg to be correctly extracted, independent of the arg order passed to model_args.
> [bugfix] Model name not extracted correctly when passing multiple args to `model_args`

- lm_eval/api/task.py
- Fewshot logging info contained attributes with numpy `int64` values which are not serializable with the logger.
> Cast numpy int64 values to py `int`s for serializability

- lm_eval/api/task.py
The way each example is constructed is currently hardcoded in `fewshot_context`. This PR refactors it out and allows the separator to be customised.
> Extract example formatting from `fewshot_context`

- setup.py
The torch version required to use the 'big model inference' is >=1.9.  "In Transformers 4.20.0, the [from_pretrained()](https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/model#transformers.PreTrainedModel.from_pretrained) method has been reworked to accommodate large models using [Accelerate](https://huggingface.co/docs/accelerate/big_modeling). This requires Accelerate >= 0.9.0 and PyTorch >= 1.9.0"
https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/model#large-model-loading
https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/model#transformers.PreTrainedModel.from_pretrained
How to reproduce an error on Colab:
https://colab.research.google.com/drive/1iBZkiV22E98GLH5PXFVExFm6-_mJVLyP?usp=sharing
I suspect this did not come up as an error since …
> Change the required torch version to >=1.9 from >= 1.7 for accelerate

- lm_eval/api/task.py
- Reverts bigscience-workshop/lm-evaluation-harness#96 as it breaks spacing assumptions in [`construct_requests` ](https://github.com/bigscience-workshop/lm-evaluation-harness/blob/484c9dbeec250a999ec590f9a945d01300fb53cc/lm_eval/api/task.py#L431)
cc @samsontmr
> Revert "Extract example formatting from `fewshot_context`"

- lm_eval/models/huggingface.py
- Updates `"lm_head"` key check to use dict-based existence operator,`in`, as `hf_device_map` is a dict.
> Update `"lm_head"` device map condition

- lm_eval/tasks/__init__.py
- lm_eval/tasks/wmt.py
- Re-adds `wmt` to the task registry now that it is available in `promptsource/eval-hackathon`.
- Adds all `wmt` years with prompt templates from `promptsource`.
> Re-add `wmt` to registry and include more years

- lm_eval/tasks/e2e_nlg_cleaned.py
- lm_eval/tasks/superglue.py
- lm_eval/tasks/tydiqa.py
- Add unpacking to force filtering invalid prompts when `promptsource` doesn't properly return a target on `apply`.
- Related Issue: #65
> Add unpacking to trigger invalid `promptsource` docs

- lm_eval/models/huggingface.py
- Fixes off-by-one truncation error whereby contexts and targets that exceed the `max_length` of an `AutoSeq2SeqLM` are shortened to `max_length - 1` as opposed to `max_length`
> Truncate seq2seq to `max_length`

- lm_eval/models/huggingface.py
- Removes `print`s that have slipped through.
> Remove `AutoSeq2SeqLM` prints

- lm_eval/models/huggingface.py
- Passing `None` to the optional `subfolder` argument of `AutoTokenizer.from_pretrained` is broken. This hacks in a subfolder specification into the `revision` arg as done in the `AutoModel<>.from_pretrained` initializer.
> Update `revision` to handle subfolder specification

- lm_eval/api/model.py
- lm_eval/models/huggingface.py
- lm_eval/tasks/__init__.py
- main.py
the previous implementation was slightly incorrect due to padding on input_ids I think
Would have to e.g. sum across the attention mask to determine the shortest sequence. Instead it's cleaner to just set it to None imo.
You may not want to merge the mlsum changes though
> Revert option for minimum generation length

- README.md
- lm_eval/api/utils.py
- lm_eval/evaluator.py
- main.py
- scripts/agg2slim.py
- scripts/make_gpt2_test_cases.py
- scripts/write_out.py
- tests/test_evaluator.py
- tests/test_misc.py
- tests/test_models_huggingface.py
- tests/test_models_openai_completions.py
- tests/test_tasks.py
- tests/test_version_stable.py
- Hard-codes the seed as in the [main EleutherAI harness](https://github.com/EleutherAI/lm-evaluation-harness/blob/b0b76d87fc84b2bfdfa88b71ce4592f35f707428/lm_eval/evaluator.py#L56) to remove an added source of non-deterministic behavior. Note this removes the optional seed arg in the CLI.
- Moves seed setter and random number generator getter into the `evaluate` function to ensure library users properly handle the `numpy`, `random`, etc. seeding.
cc @samsontmr for input since we've run into repro issues with seeding together.
> Hard-code `seed`s to reduce non-deterministic behavior

- lm_eval/api/utils.py
- Lazily import `pytest` to avoid run time errors when pip installing at the user-level (i.e.  when installing via `pip install -e .` instead of `pip install -e ".[dev]"`)
> Lazy import `pytest` in utils module

- lm_eval/models/huggingface.py
- tests/test_models_huggingface.py
the current implementation of `MultiTokenEOSCriteria` causes `model.generate()` to terminate whenever a stop token is generated for the first example in the batch. This is due to `last_token_id` (the generated token) being always retrieved from the first example: 
```
last_token_id = input_ids[0, -self.sequence_id_len :]
```
This PR modifies `MultiTokenEOSCriteria` to compare and track the generated tokens of each example in the batch and only return `True` when the model has generated a stop token for all examples .
> Fix stopping criteria to avoid early termination of generation

- main.py
- Creates more detailed output paths when running the main CLI.
Example:
```sh
slim.model=gpt2.task=wnli.templates=confident,imply.fewshot=0.batchsize=20.seed=1234.timestamp=2022-09-02T21:10:17.json
``` 
as opposed to the previous format,
```sh
slim-gpt2_wnli_confident,imply_0_1234_2022-09-02T20:34:51.595010.json
```
> Add arg name separators to output paths

- lm_eval/models/huggingface.py
- tests/test_models_huggingface.py
- Adds a `add_special_tokens` property to the `HuggingFaceAutoLM` base class to allow users to specify whether or not model inputs should be encoded with special tokens. 
- Previously, special tokens were omitted from the tokenization of inputs/labels for Seq2Seq models, which most likely resulted in sub-optimal/unfair evaluations.
- The defaults are now:
- `add_special_tokens=False` for **causal** models and
- `add_special_tokens=True` for **seq2seq** models
- Updates seq2seq model unit tests to reflect this change.
> Add a `add_special_tokens` property to the `HuggingFaceAutoLM` base class

- lm_eval/models/huggingface.py
- Make `AutoConfig` and `AutoTokenizer` classes more configurable through class attributes to allow for convenient custom adapters. 
- Feature request from @samsontmr
> Add `AutoConfig` and `AutoTokenizer` class attributes

- lm_eval/models/huggingface.py
- Loosens `add_special_tokens` argument constraint for causal models.
- Previously, if a user constructed a causal model with `add_special_tokens=False` the assertion would raise an error even though this is an acceptable arg value.
> Loosen `add_special_tokens` arg assertion

- lm_eval/api/utils.py
* This PR changes the `MutableMapping` import from `collections`  to `collections.abc` as the former no longer works for  Python >=3.10 making the harness unusable for such versions.
> Update deprecated `collections.MutableMapping `

- lm_eval/evaluator.py
* This PR re-adds a stdout handler to the evaluator logger to stream progress labels to the console. Previously, only `tqdm` progress bars were displayed.
> [fix] Add `stdout` handler to evaluator logger

- lm_eval/tasks/__init__.py
- lm_eval/tasks/diabla.py
- lm_eval/tasks/flores_101.py
Added new tasks to be used in the fewshot setting: 
- DiaBLa_1_shot_context: (only 1-shot), takes the previous sentence as context (if available)
- flores_101_mt_fewshot_fr2en: takes fr2en examples for fewshot
- flores_101_mt_fewshot_hi2en: takes hi2en examples for fewshot
- flores_101_mt_fewshot_fr2ar: takes fr2ar examples for fewshot
- flores_101_mt_fewshot_wmt_fr2en: takes fr2en examples from the wmt dev set for fewshot
> Added special few-shot examples for DiaBLa and Flores

- lm_eval/api/task.py
This PR fixes a bug in which, under rare circumstances, few-shot examples could contain the same example as the prompt to be evaluated.  The comparison used to prevent such cases: `if self.invalid_doc_for_prompt(docs[idx]) or docs[idx] == prompt` ([this](https://github.com/bigscience-workshop/lm-evaluation-harness/blob/00bb6f162b10049f2a6b44764dec1fb0a797762c/lm_eval/api/task.py#L358) line) is incorrect because every `prompt` contains a `doc_id` key from evaluation pre-processing (see [this](https://github.com/bigscience-workshop/lm-evaluation-harness/blob/00bb6f162b10049f2a6b44764dec1fb0a797762c/lm_eval/evaluator.py#L166) line) that is not present in the few-shot `docs` - thus invalidating the check.
__NOTE__: This only occurs when the …
> [fix] Skip `doc_id` in few-shot prompt comparison

- lm_eval/tasks/flores_101.py
This PR adds missing `dev` and `devtest` data splits to the `flores_101` tasks.
> Add all available doc splits to `flores_101`

- README.md
- lm_eval/api/task.py
- lm_eval/api/utils.py
- lm_eval/evaluator.py
- lm_eval/models/__init__.py
- lm_eval/tasks/__init__.py
- main.py
- tests/test_tasks.py
This PR adds support for passing `Task` constructor arguments through the CLI; in the same way model arguments are currently handled via `model_args`. This allows users to customize task instantiation from `main.py` by, say, setting the task's `example_separator` option.
Example:
```bash
python3 main.py \
--model_api_name "hf-seq2seq" \
--model_args pretrained=google/t5-small-lm-adapt,add_special_tokens=True \
--task_name "wsc" \
--task_args example_separator="\n++++\n",text_target_separator="   " \
--template_name "the pronoun refers to" \
--device cpu --batch_size 10 --limit 50 --num_fewshot 1
```
CC: @samsontmr who requested this feature.
> [feature] Add task constructor arg support to CLI
